project:
  type: website

website:
  title: "House Income Prices"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "2019"
        href: 2019.qmd
      - text: "2020"
        href: 2020.qmd
      - text: "2021"
        href: 2021.qmd
      - text: "2022"
        href: 2022.qmd
      - text: "2023"
        href: 2023.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



